version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.4
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run unit tests
          command: |

  build2:
    docker:
      - image: circleci/python:3.8.4
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run unit tests
          command: |    
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - build2




    

